// This file was generated by cubinhos embed.
// Do not edit this file.
//
// To use this file in your project, you just need to link
// this source file by adding it to your source files. To
// use it in an EmbeddedArchive, you just need to construct
// an EmbeddedArchive with the data name 'assets'

#include <cubos/core/data/embedded_archive.hpp>

using cubos::core::data::EmbeddedArchive;

static const uint8_t fileData3[] = { 0x62, 0x61, 0x7a, 0xa, };
static const uint8_t fileData4[] = { 0x66, 0x6f, 0x6f, 0xa, };

static const EmbeddedArchive::Data::Entry entries[] = {
    { "", true, 0, 0, 2, nullptr, 0 },
    { "bar", true, 1, 4, 3, nullptr, 0 },
    { "baz.txt", false, 2, 0, 0, fileData3, sizeof(fileData3) },
    { "foo.txt", false, 1, 0, 0, fileData4, sizeof(fileData4) },
};

static const EmbeddedArchive::Data embeddedArchiveData = {
    entries,
    sizeof(entries) / sizeof(entries[0]),
};

class DataRegister
{
public:
    DataRegister()
    {
        EmbeddedArchive::registerData("assets", embeddedArchiveData);
    }
};

static DataRegister dataRegister;
