// This file was generated by quadrados embed.
// Do not edit this file.
//
// To use this file in your project, you just need to link
// this source file by adding it to your source files. To
// use it in an EmbeddedArchive, you just need to construct
// an EmbeddedArchive with the data name 'assets'

#include <cubos/core/data/fs/embedded_archive.hpp>

using cubos::core::data::EmbeddedArchive;

static const uint8_t FileData3[] = {
    0x62,
    0x61,
    0x7a,
};
static const uint8_t FileData4[] = {
    0x66,
    0x6f,
    0x6f,
};

static const EmbeddedArchive::Data::Entry Entries[] = {
    {"", true, 0, 0, 2, nullptr, 0},
    {"bar", true, 1, 4, 3, nullptr, 0},
    {"baz.txt", false, 2, 0, 0, FileData3, sizeof(FileData3)},
    {"foo.txt", false, 1, 0, 0, FileData4, sizeof(FileData4)},
};

static const EmbeddedArchive::Data EmbeddedArchiveData = {
    Entries,
    sizeof(Entries) / sizeof(Entries[0]),
};

class DataRegister
{
public:
    DataRegister()
    {
        EmbeddedArchive::registerData("assets", EmbeddedArchiveData);
    }
};

static DataRegister dataRegister;
