/// @file
/// @brief Class @ref cubos::core::data::EmbeddedArchive.
/// @ingroup core-data-fs

#pragma once

#include <map>
#include <vector>

#include <cubos/core/data/fs/archive.hpp>

namespace cubos::core::data
{
    /// @brief Archive implementation which reads data embedded in the application. Meant to be
    /// used with the `quadrados embed` tool.
    ///
    /// Can be used to create single-file applications, where all the data is embedded in the
    /// executable.
    ///
    /// This archive accesses a global map of data, where embedded data can be registered with a
    /// given name. Then, to access that data, an instance of this archive is created pointing to
    /// that name.
    ///
    /// The `embed` tool generates source files which define and register that data. By linking
    /// those files into your application, you're making the data available to be accessed through
    /// an instance of this archive.
    ///
    /// @ingroup core-data-fs
    class CUBOS_CORE_API EmbeddedArchive : public Archive
    {
    public:
        /// @brief Describes the structure of the embedded data.
        struct Data
        {
            /// @brief Describes a file entry in the embedded data.
            struct Entry
            {
                const char* name; ///< Name of the file entry.
                bool isDirectory; ///< Whether the entry is a directory.

                std::size_t parent;  ///< Index of the parent directory.
                std::size_t sibling; ///< Index of the next sibling.
                std::size_t child;   ///< Index of the first child.

                const void* data; ///< Data of the file entry.
                std::size_t size; ///< Size of the data.
            };

            const Entry* entries;   ///< Entries of the embedded archive.
            std::size_t entryCount; ///< Number of entries in the embedded archive.
        };

        /// @brief Constructs pointing to the data with the given @p name.
        ///
        /// Aborts if no data with the given @p name was registered.
        ///
        /// @param name Name of the data the embedded archive is going to access.
        EmbeddedArchive(const std::string& name);
        ~EmbeddedArchive() override = default;

        /// @brief Registers embedded archive data, which must remain valid for the lifetime of the
        /// application.
        ///
        /// This function is called by the code generated by the `embed` tool.
        ///
        /// @param name Name of the embedded archive data.
        /// @param data Embedded archive data.
        static void registerData(const std::string& name, const Data& data);

        // Archive interface implementation.

        std::size_t create(std::size_t parent, std::string_view name, bool directory = false) override;
        bool destroy(std::size_t id) override;
        std::string name(std::size_t id) const override;
        bool directory(std::size_t id) const override;
        bool readOnly() const override;
        std::size_t parent(std::size_t id) const override;
        std::size_t sibling(std::size_t id) const override;
        std::size_t child(std::size_t id) const override;
        std::unique_ptr<memory::Stream> open(std::size_t id, File::Handle handle, File::OpenMode mode) override;

    private:
        /// @brief Accesses the registry of embedded archive data.
        /// @return Reference to the registry.
        static std::map<std::string, const Data&>& registry();

        const Data* mData; ///< Embedded archive data.
    };
} // namespace cubos::core::data
