name: 🪟 Build Engine Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_DIR: "${{ github.workspace }}/.ccache"
  CCACHE_COMPILERTYPE: msvc

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Create Build Env
      run: cmake -E make_directory ${{github.workspace}}\build

    - name: Download ccache
      shell: cmake -P {0}
      run: |
        set(ccache_url "https://github.com/cristianadam/ccache/releases/download/v${{ env.ccache_version }}/${{ runner.os }}.tar.xz")
        file(DOWNLOAD "${ccache_url}" ./ccache.tar.xz SHOW_PROGRESS)
        execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ccache.tar.xz)
        if(ret AND NOT ret EQUAL 0)
          message( FATAL_ERROR "Bad exit status")
        endif()

    - uses: actions/cache@v3
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ env.CCACHE_COMPILERTYPE }}-${{ env.BUILD_TYPE }}-${{ github.ref }}
        restore-keys: |
          ccache-${{ env.CCACHE_COMPILERTYPE }}-${{ env.BUILD_TYPE }}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}\build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_CORE_SAMPLES=ON -DBUILD_CORE_TESTS=ON -DBUILD_ENGINE_SAMPLES=ON -DUSE_CLANG_TIDY=OFF

    - name: CCache Prolog
      run: |-
        ccache -s # Print current cache stats
        ccache -z # Zero cache entry

    - name: Build
      run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

    - name: CCache Epilog
      run: |
        ccache -s # Print current cache stats

    - name: Test
      run: ${{github.workspace}}\build\core\tests\Release\cubos-core-tests.exe
      
