name: 🪟 Build Engine Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  CCACHE_VERSION: 4.8.3
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_DIR: "${{ github.workspace }}/.ccache"
  CCACHE_COMPILERTYPE: msvc

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        choco install ccache --version ${{ env.CCACHE_VERSION }}
        python -m pip install jinja2

    - name: Get timestamp
      shell: bash
      id: ccache_vars
      run: |
        echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ env.CCACHE_COMPILERTYPE }}-${{ env.BUILD_TYPE }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
        restore-keys: |
          ccache-${{ env.CCACHE_COMPILERTYPE }}-${{ env.BUILD_TYPE }}-${{ github.ref }}-
          ccache-${{ env.CCACHE_COMPILERTYPE }}-${{ env.BUILD_TYPE }}-
          ccache-${{ env.CCACHE_COMPILERTYPE }}-
          ccache-

    - name: Create Build Env
      run: cmake -E make_directory ${{github.workspace}}\build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}\build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_CORE_SAMPLES=ON -DBUILD_CORE_TESTS=ON -DBUILD_ENGINE_TESTS=ON -DBUILD_ENGINE_SAMPLES=ON -DUSE_CLANG_TIDY=OFF -DCCACHE_VERSION="${{env.CCACHE_VERSION}}"

    - name: CCache Prolog
      run: |-
        ccache -s # Print current cache stats
        ccache -z # Zero cache entry

    - name: Build
      run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

    - name: CCache Epilog
      run: |
        ccache -s # Print current cache stats

    - name: Test Core
      run: ${{github.workspace}}\build\Release\cubos-core-tests.exe
      
    - name: Test Engine
      run: ${{github.workspace}}\build\Release\cubos-engine-tests.exe
