name: 🏷️ Copy Labels

on:
  pull_request:
    branches: [ main ]

jobs:
  copy-labels:
    runs-on: ubuntu-22.04
    name: Copy labels from linked issues
    steps:
      - name: copy-labels
        uses: michalvankodev/copy-issue-labels@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}